on:
  pull_request:
    type: closed

jobs:
  celebrate:
    runs-on: ubuntu-latest
    name: Celebrate merged PRs
    steps:
      - name: Celebrate
        id: celebrate
        uses: gabro/gif-celebration-action@master
        if: github.action == 'closed' && github.pull_request.merged == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
