on: [pull_request]

jobs:
  celebrate:
    runs-on: ubuntu-latest
    name: Celebrate merged PRs
    steps:
      - name: Celebrate
        id: celebrate
        uses: gabro/gif-celebration-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
